name: RswiftWithXcodeGen
settings:
  IPHONEOS_DEPLOYMENT_TARGET: 10.2
targets:
  RswiftWithXcodeGen:
    type: application
    platform: iOS
    sources: Sources
    settings:
        base:
          PRODUCT_BUNDLE_IDENTIFIER: me.gin0606.RswiftWithXcodeGen
          IPHONEOS_DEPLOYMENT_TARGET: 10.2
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
          DEVELOPMENT_TEAM: G89J8GUEJZ
    prebuildScripts:
      - name: Run R.swift
        script: |
          ${PODS_ROOT}/R.swift/rswift generate ${SRCROOT}/Sources
